// import Input from "./controlled-input/Input"
// import Toggle from "./toggle-btn/Toggle"
// import ShowHide from "./show-hide/ShowHide"
// import CharCount from "./char-count/CharCount"
// import Form from "./form/Form"
// import Combine from "./combine-output/Combine"
// import Settings from "./checbox/Settings"
// import AddItem from "./add/AddItem"
// import Highlight from "./highlight/Highlight"
// import Filter from "./filter/Filter"
// import Undo from "./undo/Undo"
// import Tabs from "./tabs/Tabs"
// import MultiForm from "./multi-step-form/MultiForm"
// import Todo from "./todo/Todo"
// import Todo from "./todo-reducer/Todo"
// import Counter from "./reducers/counter-reducer/Counter"
// import StepCounter from "./reducers/step-counter/StepCounter"
// import ShoppingCart from "./reducers/shopping-cart/ShoppingCart"
// import MainContext from "./context/MainContext"
// import MainTheme from "./theme-context/MainTheme"
import RefCount from "./refs/ref-count/RefCount"

export default function App() {
  return <RefCount />
}